### ISSUE TITLE
Compiler failure: * marked ‘override’, but does not override

### ISSUE THREAD

**Issue by naclander** [jimm/vcv-jimm#1]
This looks like a really cool plugin, and in the process of compiling it to work with my version of rack I've noticed the following compiler error, running on `gcc (Ubuntu 7.2.0-8ubuntu3) 7.2.0`

```bash
nathan@macbook-studio:~/Projects/Rack/plugins/vcv-jimm$ make -j9
g++  -fPIC -I../../include -I../../dep/include -DVERSION=0.5.0 -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN  -Wsuggest-override -std=c++11 -c -o build/src/Jimm.cpp.o src/Jimm.cpp
g++  -fPIC -I../../include -I../../dep/include -DVERSION=0.5.0 -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN  -Wsuggest-override -std=c++11 -c -o build/src/Arpeggiator.cpp.o src/Arpeggiator.cpp
src/Arpeggiator.cpp:88:7: error: ‘void Arpeggiator::onReset()’ marked ‘override’, but does not override
  void onReset() override {
       ^~~~~~~
src/Arpeggiator.cpp:93:7: error: ‘void Arpeggiator::onRandomize()’ marked ‘override’, but does not override
  void onRandomize() override {
       ^~~~~~~~~~~
../../compile.mk:53: recipe for target 'build/src/Arpeggiator.cpp.o' failed
make: *** [build/src/Arpeggiator.cpp.o] Error 1
make: *** Waiting for unfinished jobs....

```

**Comment by jimm** [comment]
@naclander thanks for the issue. I'll fix this right away.

**Comment by jimm** [comment]
Interesting: on the Mac, if I remove the `override` keyword from those two methods then I get the warnings below. Those methods do override the `virtual void` methods defined in `struct Module` in `engine.hpp`.

I'm not a C++ expert, so I'm not sure what to do. I'd rather avoid platform-specific code if I can. Do you have any suggestions, @naclander?
```
c++  -std=c++11 -stdlib=libc++  -fPIC -I../../include -I../../dep/include -DVERSION=0.5.0 -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.7 -c -o build/src/Arpeggiator.cpp.o src/Arpeggiator.cpp
src/Arpeggiator.cpp:88:7: warning: 'onReset' overrides a member function but is not
      marked 'override' [-Winconsistent-missing-override]
        void onReset() {
             ^
../../include/engine.hpp:73:15: note: overridden virtual function is here
        virtual void onReset() {}
                     ^
src/Arpeggiator.cpp:93:7: warning: 'onRandomize' overrides a member function but is
      not marked 'override' [-Winconsistent-missing-override]
        void onRandomize() {
             ^
../../include/engine.hpp:75:15: note: overridden virtual function is here
        virtual void onRandomize() {}
                     ^
2 warnings generated.
```

**Comment by naclander** [comment]
I'm not a C++ expert either, but when I forced make to use the clang compiler I was able to compile succesfully. Maybe state in the README that only clang is supported and include `-stdlib=libc++` in the Makefile ( I got that from [here](https://stackoverflow.com/questions/9732707/using-clang-in-makefile-in-place-of-g) )

I now have it compiled, but I'm still not able to see the module inside vcv rack. This might be an unrelated issue though.

**Comment by phdsg** [comment]
likely a conflict of  rack versions. master/0.5 aren't compatible

see here: https://github.com/VCVRack/Rack/issues/258

**Comment by jimm** [comment]
@phdsg thanks for the info. That might be the issue, I don't know. I'm compiling against master.

@naclander, are you compiling against rack's current master? The Arpeggiator.cpp source started as a direct copy of the fundamental plugin's SEQ3.cpp source. I thought I might have moved those functions out of the module definition, but just checked to make sure and they are declared and defined exactly as they are in the original code.

**Comment by naclander** [comment]
@jimm Yup, I'm up to date with master. Again, could be compatabilities with the platform I'm running. I'll keep playing around with the module to see if I can get it running. If anyone else reports success of running this on Linux, its most likely something specific to my system.

**Comment by jimm** [comment]
You could also try setting CXX or CC on the command line when you build the plugin; the makefile will pick that up. For example,
```
CXX=foobar make
$ foobar --std=c++11 --stdlib=libc++ ...
...
make: foobar: No such file or directory
```

**Comment by jimm** [comment]
[Edit: ignore this comment and move on to the next one, please.]

Today on /r/vcvrack there's a discussion called "Using 'Make' in windows to compile free plugins" at https://www.reddit.com/r/vcvrack/comments/7o1bse/using_make_in_windows_to_compile_free_plugins/. It points to the VCV Rack README at https://github.com/VCVRack/Rack which states that MSYS2/mingw64/pacman is the supported toolchain for Windows.

Forgive my ignorance of Windows *nix-style development (I haven't done any for around a decade). Are the tools you're using the same? If not, then I think it might make sense to see how compilation of Arpeggiator goes with that toolchain.

If the difference is the toolchain you're using, then I think it makes sense to close this ticket. If you are using the same toolchain, then it might make sense for either you or I to open a ticket with the VCV Rack project telling them about this `override` issue.

**Comment by jimm** [comment]
Ignore my previous Windows-specific comment, since you're on Linux :-) VCV Rack's README says to use `gcc`, `make`, `cmake` (and `tar` and `unzip`).

I don't know the differences between `g++`, `gcc`, and `clang`.

**Comment by jimm** [comment]
@naclander can you please try the rack-v0.6-update branch when you have time? I plan to merge that into master soon. I'm getting no errors or warnings while compiling.

**Comment by naclander** [comment]
Currently don't have access to my Rack machine, I'll test this when I get the chance. Feel free to close the issue and reopen if its still a prblem.
