### ISSUE TITLE
Bugfixes for outputs 2 and 3

### ISSUE THREAD

**Issue by jsmonzani** [jimm/vcv-jimm#3]
Hey,
Cool pretty arpegiator. There are some issues with output from the 2nd and 3rd row, though.

Lines 368/369 should be updated with proper ROW2/3_OCTAVE_PARAMs:
		addParam(createParam<RoundTinyBlackSnapKnob>(Vec(squishedPortX[i]-2 + 8, 198+16), module, Arpeggiator::ROW2_OCTAVE_PARAM + i, 0.0, 7.0, 4.0));
		addParam(createParam<RoundTinyBlackSnapKnob>(Vec(squishedPortX[i]-2 + 8, 240+16), module, Arpeggiator::ROW3_OCTAVE_PARAM + i, 0.0, 7.0, 4.0));

Cheers!

**Comment by jimm** [comment]
@jsmonzani Thank you for the fix. Sorry it took so long for me to get to this. Your fix will be in the next release. I still need to replace some outdated widget-creation code.
