### ISSUE TITLE
typo in 0.6 update

### ISSUE THREAD

**Issue by phdsg** [jimm/vcv-jimm#4]
was getting a linker error when testing the 0.6 branch.
just a typo. builds and loads fine after fixing. nice work.
https://github.com/jimm/vcv-jimm/blob/f2b52b7950a93c9c798484c9dc6009139a3d36b1/src/Jimm.cpp#L9

**Comment by jimm** [comment]
D'oh! Thank you, @phdsg, for finding that. I've updated the source locally and will push with the next set of fixes.
